export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const IMAGE_LOADED_SIGNUP = 'IMAGE_LOADED_SIGNUP';
export const CLEAR_SIGNUP_STATE = 'CLEAR_SIGNUP_STATE';

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const IMAGE_LOADED_SIGNIN = 'IMAGE_LOADED_SIGNIN';
export const CLEAR_SIGNIN_STATE = 'CLEAR_SIGNIN_STATE';
