// actions/signUp.js
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const IMAGE_LOADED_SIGNUP = 'IMAGE_LOADED_SIGNUP';
export const CLEAR_SIGNUP_STATE = 'CLEAR_SIGNUP_STATE';

// actions/signIn.js
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const IMAGE_LOADED_SIGNIN = 'IMAGE_LOADED_SIGNIN';
export const CLEAR_SIGNIN_STATE = 'CLEAR_SIGNIN_STATE';

// actions/auth.js
export const CHECK_AUTH = 'CHECK_AUTH';

// actions/host.js
export const CHANGE_STEP = 'CHANGE_STEP'
export const CHANGE_PROPERTY_AREA = 'CHANGE_PROPERTY_AREA';
export const CHANGE_PROPERTY_TYPE = 'CHANGE_PROPERTY_TYPE';
export const INC_GUEST_CAPACITY = 'INC_GUEST_CAPACITY';
export const DEC_GUEST_CAPACITY = 'DEC_GUEST_CAPACITY';
export const INC_ROOMS = 'INC_ROOMS';
export const DEC_ROOMS = 'DEC_ROOMS';
export const INC_BEDS = 'INC_BEDS';
export const DEC_BEDS = 'DEC_BEDS';
export const ADD_AMENITY = 'ADD_AMENITY';
export const REMOVE_AMENITY = 'REMOVE_AMENITY';
export const ADD_FACILITY = 'ADD_FACILITY';
export const REMOVE_FACILITY = 'REMOVE_FACILITY';
export const CHANGE_PROPERTY_NAME = 'CHANGE_PROPERTY_NAME';
export const CHANGE_PROPERTY_DESC = 'CHANGE_PROPERTY_DESC';
export const SET_LOCATION = 'SET_LOCATION';
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const CHANGE_STATE = 'CHANGE_STATE';
export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_STREET = 'CHANGE_STREET';
export const CHANGE_NUMBER = 'CHANGE_NUMBER';
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const CHANGE_SCHEDULE = 'CHANGE_SCHEDULE';
export const ADD_RULE = 'ADD_RULE';
export const REMOVE_RULE = 'REMOVE_RULE';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const REMOVE_LANGUAGE = 'REMOVE_LANGUAGE';
export const CLEAR_STORE = 'CLEAR_STORE';

// actions/map.js
export const INIT_LOCATION = 'INIT_LOCATION';
export const SET_LOCATION_FROM_IP = 'SET_LOCATION_FROM_IP';
export const SET_COUNTRY_FROM_IP = 'SET_COUNTRY_FROM_IP';
export const SET_COUNTRY_CODE_FROM_IP = 'SET_COUNTRY_CODE_FROM_IP';
export const FETCH_POSTS_BY_COUNTRY = 'FETCH_POSTS_BY_COUNTRY';
export const SET_POSTS = 'SET_POSTS';
export const SORT_POSTS = 'SORT_POSTS';
